version: '3'

services:
  web:
    build:
      context: .
    ports:
      - '5000:5000'
    environment:
      - DOCKER_ENVIRONMENT=True
    env_file:
      - ../.env
    volumes:
      - .:/app
    command: ["hypercorn", "quart_app.py:app", "--bind", "0.0.0.0:5000"]

  redis:
    image: "redis:latest"
